CREATE OR REPLACE PROCEDURE GMAHADEVAN_DB.GMAHADEVAN_SCHEMA.DimAccountingDocumentHeader()
    RETURNS VARCHAR(16777216)
    LANGUAGE PYTHON
    RUNTIME_VERSION = '3.10'
    PACKAGES = ('snowflake-snowpark-python')
    HANDLER = 'DimAccountingDocumentHeader.main'
    IMPORTS = ('@GMAHADEVAN_DB.GMAHADEVAN_SCHEMA.GIT_NOTEBOOK_REPO/branches/dev/GM-2/DIMWELL/notebook_app.ipynb')
    EXECUTE AS OWNER
    ;