# This is a basic workflow to help you get started with Actions

name: DEPLOY_STORED_PROC

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   dev_db: GMAHADEVAN_DB
#   dev_schema: GMAHADEVAN_SCHEMA
#   prod_db: PROD_DB  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set environment variables based on branch
        id: set-env-vars
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          # change the below to prod values. keeping it to dev, to not fail in pr merge to master
            echo "dev_db=GMAHADEVAN_DB" >> $GITHUB_ENV
            echo "dev_schema=GMAHADEVAN_SCHEMA" >> $GITHUB_ENV
            echo "Environment variable prod_db set for main branch."
          else
            echo "dev_db=GMAHADEVAN_DB" >> $GITHUB_ENV
            echo "dev_schema=GMAHADEVAN_SCHEMA" >> $GITHUB_ENV
            echo "Environment variable dev_db, dev_schema set for a feature branches."
          fi

      - name: Install Python packages
        run: pip install -r requirements.txt
      
      - uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          # PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PASSPHRASE }} 
          # SNOWFLAKE_CONNECTIONS_MYCONNECTION_AUTHENTICATOR: SNOWFLAKE_JWT
          # SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: GITHUB_ACTIONS
          # SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          # SNOWFLAKE_CONNECTIONS_MYCONNECTION_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

        run: |
          echo "dev_db is: $dev_db"
          echo "dev_schema is: $dev_schema"
          echo "Snowflake account : ${{ vars.SNOWFLAKE_ACCOUNT }}"
          # snow --version

          # snow connection test -x -v  --accountname ${{ vars.SNOWFLAKE_ACCOUNT }} --role git_devops --user GIT_CICD --private-key-file ~/Documents/git_user_pvt_key.p8 --authenticator SNOWFLAKE_JWT --database gmahadevan_test --schema gmahadevan_schema
          

          
